version: "3"

networks:
  app:
    driver: bridge

services:
  postgres:
    container_name: "pg"
    image: "postgres:9.6"
    volumes:
     - "./postgresql.conf:/postgresql.conf"
    networks:
     - app
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_DB=ideas
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=secret
    command: "postgres -c config_file=/postgresql.conf"
  pghero:
    container_name: "pghero"
    image: "ankane/pghero"
    networks:
     - app
    ports:
     - 5858:8080
    environment:
     - DATABASE_URL=postgres://postgres:secret@postgres:5432/ideas
  mongodb:
    container_name: "mongo"
    image: "mongo:3.0"
    ports:
     - "27017:27017"
